name: auto-approve

on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  approve:
    runs-on: ubuntu-latest
    name: Auto-Approve PR
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code Repository
        uses: actions/checkout@v5.0.0
      - name: Auto-Approve PR
        uses: ./
        with:
          bot_token: ${{ secrets.P6_A_GH_TOKEN }}
